name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run build
      - name: ESLint
        run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HORIZON_HOST }}
          username: ${{ secrets.HORIZON_USERNAME }}
          key: ${{ secrets.HORIZON_SSHKEY }}
          script: |
            cd horizon
            git pull
            npm install
            npm run build
            npm run scrape-games3
